export enum ActionType {
  FETCH_USERS = "FETCH_USERS ",
  FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS",
  FETCH_USERS_FAILUR = "FETCH_USERS_FAILUR",

  CREATE_USERS = "CREATE_USERS ",
  CREATE_USERS_SUCCESS = "CREATE_USERS_SUCCESS",
  CREATE_USERS_FAILUR = "CREATE_USERS_FAILUR",
}
